### PR TITLE
Feat: NativeScript 7 Support

### PR DESCRIPTION
**Pull request by bradmartin**
#### Description
Adds support for NativeScript 7

#### Changes
- update tsconfigs
- update imports
- update dependencies for dev and plugin

### CODE REVIEW

**Comment by bradmartin** [comment]
Leaving this as a draft because one plugin `nativescript-urlhandler` needs to merge a PR that adds NS7 support. https://github.com/hypery2k/nativescript-urlhandler/pull/116 It would be possible to just add a fork of that, but I'm unaware how the Kinvey team wants to handle that.

**Comment by bradmartin** [comment]
I'm actually not even sure what the purpose of the `popup` is within this plugin for NativeScript 🤔

**Comment by bradmartin** [comment]
I've published a working version under `@bradmartin/kinvey-nativescript-sdk` with some minor modifications to get this working for majority of use cases for NS7.

**Comment by steinerj** [comment]
> I'm actually not even sure what the purpose of the `popup` is within this plugin for NativeScript 🤔

Not sure how the popup relates to the urlhandler, but the popup is used for Kinvey's federated login mechanism "MIC" - https://devcenter.kinvey.com/nativescript/guides/mobile-identity-connect

**Comment by ventsislav-georgiev** [comment]
@bradmartin Is there a way to make the library compatible to be used with both NS7 and NS6?

**Comment by bradmartin** [comment]
I don't believe so, NS7 was a breaking change, so it would require a major version change. Mainly for the ES2017 support set in the tsconfig. Also several imports were changed, which also goes in line with the ES2017 (full tree-shaking benefit) to use the new `@nativescript/core` package over the older `tns-core-modules`.

I suppose there might be a way to make it work with some approach, but I'd say the benefit isn't worth the effort or maintenance in the future.

**Comment by ventsislav-georgiev** [comment]
@bradmartin the tests couldn't run from this branch so I moved it to: https://github.com/Kinvey/js-sdk/pull/574
Thank you for the PR!

**Pull request merged**
