### PR TITLE
Update webpack.config.js for each SDK

### PR DESCRIPTION
**Pull request by thomasconner**
#### Description
This adds the `UglifyJSPlugin` by default to the plugins array. Some cleanup is done to the plugins for options that are not used.

### CODE REVIEW

**Comment by thomasconner** [comment]
It is common practice to install any package used in a NativeScript or Node.js application using npm. I have marked dependencies as externals since these dependencies will be installed when our SDK package is installed.

Other environments do not have these dependencies as externals because sometimes they are used outside of a package manager. For example, people will commonly just download the bundle for Angular and include it in their application. This would result in missing dependencies if they were marked as external and not included in the bundle.

**Comment by georgiwe** [comment]
Hm, okay. I think it would be simpler to bundle everything. This way we can list the SDK dependencies in one package.json file during development, instead of managing them and their versions in separate such files, because they need to be installed when using the SDK.

**Comment by thomasconner** [comment]
I ran into two issues when I tried to bundle the dependencies for the `kinvey-node-sdk`.

```
kinvey-node-sdk: WARNING in /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/formidable/lib/incoming_form.js
kinvey-node-sdk: 1:43-50 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/formidable/lib/incoming_form.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/formidable/lib/index.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/superagent/lib/node/index.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/pubnub/lib/networking/modules/web-node.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/pubnub/lib/node/index.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/src/core/live/live-service.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/src/core/live/index.js
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/src/core/index.js
kinvey-node-sdk:  @ ./index.js
kinvey-node-sdk: WARNING in /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/es6-promise/dist/es6-promise.js
kinvey-node-sdk: Module not found: Error: Can't resolve 'vertx' in '/Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/es6-promise/dist'
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/node_modules/es6-promise/dist/es6-promise.js 138:16-26
kinvey-node-sdk:  @ /Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/SDK/src/node/http.js
kinvey-node-sdk:  @ ./index.js
```

I think the best route is to keep them as external dependencies and revisit how we can prevent duplication later.

**Comment by thomasconner** [comment]
I have created https://kinvey.atlassian.net/browse/MLIBZ-2249 to capture the discussion we need to have around duplicate dependencies.

**Pull request merged**
